In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import Dense

In [2]:
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = x.reshape(-1,2).shape
print("X shape before reshaping = ",x.shape)
print("Y shape = ",y.shape)
print("X = \n",x)
print("y = \n",y)
print("X column ",x.shape[1])
print("X shape bafter reshaping = ",x.reshape(-1))
print(b)

x = tf.convert_to_tensor([[1, 2, 3], [4, 5, 6]], dtype=tf.float32)
y = tf.convert_to_tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=tf.float32)
#X&Y are converted to tensors because tf only accepts tensors but not numpy arrays


X shape before reshaping =  (2, 3)
Y shape =  (3, 3)
X = 
 [[1 2 3]
 [4 5 6]]
y = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
X column  3
X shape bafter reshaping =  [1 2 3 4 5 6]
(3, 2)


for i in range(len(y)):
    for j in range(len(y[i])):
        print(y[i][j])

In [3]:
layer_11 = Dense(3,activation='sigmoid',input_shape=(3,))
a11=layer_11(x)
#Dense represents the fully connected layer
#3 represents the no.of neurons in the 1st hidden layer
#input_shape=(2,3) represents the shape of my input vector

#x0 represent the input layer
#w11 represent the weight of the 1st neuron in the 1st hidden layer
#w21 represent the weight of the 2nd neuron in the 1st hidden layer
#w31 represent the weight of the 3rd neuron in the 1st hidden layer
#a1 is the output of the 1st hidden layer
#a11=[(w1.x0+b1)+(w2.x0+b1)+(w3.x0+b1)]

layer_21 = Dense(1,activation='sigmoid')
a21=layer_21(a11)

#w12 represent the weight of the first neuron in the 2nd hidden layer
#a1 is given as the input to the 2nd hidden layer
#a2=[(w1.a1+b1)]

#The above code is equivalent to the following diagram

#                                O 
#           X0            ------>O          ------> O
#                                O 
#         input vector        provides A1         provides A2

print(len(a21))
for i in range(len(a21)):
    print(a2[i])
    if a21[i]>0.5:
        print("1")
    else:
        print("0")

c:\Users\SRK\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


2


NameError: name 'a2' is not defined

In [23]:
layer_12 = Dense(5,activation='sigmoid',input_shape=(3,))
a12=layer_12(y)

#5 represents the no.pf neurons in the 1st hidden layer
#input_shape=(3,3) represents the shape of my input vector(y)

#Y0 represent the input layer

#W11 represent the weight of the 1st neuron in the 1st hidden layer
#W21 represent the weight of the 2nd neuron in the 1st hidden layer
#W31 represent the weight of the 3rd neuron in the 1st hidden layer
#W41 represent the weight of the 4th neuron in the 1st hidden layer
#W51 represent the weight of the 5th neuron in the 1st hidden layer

#a12 is the output of the 1st hidden layer
#a12=[(w1.y0+b1)+(w2.y0+b1)+(w3.y0+b1)+(w4.y0+b1)+(w5.y0+b1)]

layer_22 = Dense(3,activation='sigmoid')
a22=layer_22(a12)

#w12 represent the weight of the 1st neuron in the 2nd hidden layer
#W22 represent the weight of the 2nd neuron in the 2nd hidden layer
#W32 represent the weight of the 3rd neuron in the 3rd hidden layer
#a12 is given as the input to the 2nd hidden layer
#a22=[(w1.a12+b1)+(w2.a12+b1)+(w3.a12+b1)]

layer_32 = Dense(1,activation='sigmoid')
a32=layer_32(a22)

#w13 represent the weight of the 1st neuron in the 3rd hidden layer
#w23 represent the weight of the 2nd neuron in the 3rd hidden layer
#w33 represent the weight of the 3rd neuron in the 3rd hidden layer
#a32 is the output of the 3rd hidden layer

#The above code is equivalent to the following diagram

#                                O 
#                                O                     O
#           Y0            ------>O             ------> O           ------> O
#                                O                     O
#                                O
#         input vector        provides A1         provides A2         provides A3 

print(len(a32))
for i in range(len(a32)):
    print(a32[i])
    if a32[i]>0.5:
        print("1")
    else:
        print("0")


3
tf.Tensor([0.36054084], shape=(1,), dtype=float32)
0
tf.Tensor([0.37331542], shape=(1,), dtype=float32)
0
tf.Tensor([0.37548113], shape=(1,), dtype=float32)
0
